import main.GameCanvas;
/*
 * Decompiled with CFR 0.152.
 */
public class T {
    public static String LoginScreen = "";
    public static String b = "";
    public static String c = "";
    public static String d = "";
    public static String e = "";
    public static String f = "";
    public static String g = "";
    public static String Item = "";
    public static String i = "";
    public static String j = "";
    public static String k = "";
    public static String Res;
    public static String m;
    public static String n;
    public static String o;
    public static String GameScreen;
    public static String q;
    public static String r;
    public static String SessionReceiver;
    public static String MyHashtable;
    public static String u;
    public static String v;
    public static String w;
    public static String x;
    public static String Message;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static String D;
    public static String E;
    public static String F;
    public static String G;
    public static String H;
    public static String I;
    public static String J;
    public static String K;
    public static String L;
    public static String M;
    public static String N;
    public static String O;
    public static String P;
    public static String Q;
    public static String R;
    public static String S;
    public static String T;
    public static String U;
    public static String V;
    public static String W;
    public static String X;
    public static String Y;
    public static String Z;
    public static String Mob;
    public static String ab;
    public static String MessageHandler;
    public static String ad;
    public static String ae;
    public static String[] Char;
    public static String ag;
    public static String ah;
    public static String ai;
    public static String aj;
    public static String ak;
    public static String al;
    public static String am;
    public static String an;
    public static String ao;
    public static String ap;
    public static String aq;
    public static String ar;
    public static String ImageCache;
    public static String at;
    public static String au;
    public static String RMS;
    public static String T;
    public static String ax;
    public static String ay;
    public static String az;
    public static String aA;
    public static String aB;
    public static String aC;
    public static String aD;
    public static String aE;
    public static String aF;
    public static String aG;
    public static String aH;
    public static String aI;
    public static String aJ;
    public static String[] aK;
    public static String[] aL;
    public static String[] aM;
    public static String[][] aN;
    public static String[][] aO;
    public static String[][] aP;
    public static String[][] aQ;
    public static String[] aR;
    public static String[] aS;
    public static String aT;
    public static String aU;
    public static String aV;
    public static String[] aW;
    public static String[] aX;
    public static String[] aY;
    public static String aZ;
    public static String ba;
    public static String Screen;
    public static String bc;
    public static String bd;
    public static String be;
    public static String bf;
    public static String bg;
    public static String bh;
    public static String bi;
    public static String bj;
    public static String bk;
    public static String bl;
    public static String bm;
    public static String ImageLoader;
    public static String bo;
    public static String bp;
    public static String bq;
    public static String Session;
    public static String ServerListScreen;
    public static String GameService;
    public static String bu;
    public static String bv;
    public static String bw;
    public static String bx;
    public static String by;
    public static String bz;
    public static String bA;
    public static String bB;
    public static String bC;
    public static String bD;
    public static String bE;
    public static String bF;
    public static String bG;
    public static String bH;
    public static String bI;
    public static String bJ;
    public static String bK;
    public static String bL;
    public static String bM;
    public static String bN;
    public static String bO;
    public static String bP;
    public static String bQ;
    public static String bR;
    public static String bS;
    public static String bT;
    public static String bU;
    public static String bV;
    public static String bW;
    public static String bX;
    public static String bY;
    public static String bZ;
    public static String ca;
    public static String cb;
    public static String Npc;
    public static String cd;
    public static String[] ItemMap;
    public static String[] cf;
    public static String[] cg;
    public static String[] ch;
    public static String[] ci;
    public static String[] cj;
    public static String[] ck;
    public static String cl;
    public static String cm;
    public static String cn;
    public static String co;
    public static String cp;
    public static String cq;
    public static String cr;
    public static String cs;
    public static String ct;
    public static String cu;
    public static String cv;
    public static String cw;
    public static String cx;
    public static String cy;
    public static String cz;
    public static String cA;
    public static String cB;
    public static String cC;
    public static String cD;
    public static String cE;
    public static String cF;
    public static String cG;
    public static String cH;
    public static String cI;
    public static String cJ;
    public static String cK;
    public static String cL;
    public static String cM;
    public static String cN;
    public static String cO;
    public static String cP;
    public static String cQ;
    public static String cR;
    public static String cS;
    public static String cT;
    public static String cU;
    public static String cV;
    public static String cW;
    public static String cX;
    public static String cY;
    public static String cZ;
    public static String da;
    public static String db;
    public static String dc;
    public static String dd;
    public static String de;
    public static String df;
    public static String[] BaseCanvas;
    public static String[] dh;
    public static String[] mFont;
    public static String[] dj;
    public static String[] dk;
    public static String[] dl;
    public static String[] dm;
    public static String[] dn;
    public static String cfr_renamed_0;
    public static String dp;
    public static String dq;
    public static String dr;
    public static String[] ds;
    public static String dt;
    public static String du;
    public static String dv;
    public static String dw;
    public static String dx;
    public static String dy;
    public static String dz;
    public static String dA;
    public static String dB;
    public static String dC;
    public static String dD;
    public static String dE;
    public static String dF;
    public static String dG;
    public static String dH;
    public static String dI;
    public static String dJ;
    public static String dK;
    public static String dL;
    public static String dM;
    public static String dN;
    public static String dO;
    public static String dP;
    public static String dQ;
    public static String dR;
    public static String dS;
    public static String dT;
    public static String dU;
    public static String dV;
    public static String dW;
    public static String dX;
    public static String dY;
    public static String dZ;
    public static String ea;
    public static String eb;
    public static String ec;
    public static String WeatherEffect;
    public static String ee;
    public static String ef;
    public static String eg;
    public static String eh;
    public static String ei;
    public static String ej;
    public static String ek;
    public static String MyVector;
    public static String SplashScreen;
    public static String mGraphics;
    public static String Position;
    public static String ep;
    public static String eq;
    public static String er;
    public static String es;
    public static String et;
    public static String eu;
    public static String ev;
    public static String ew;
    public static String ex;
    public static String ey;
    public static String ez;
    public static String eA;
    public static String eB;
    public static String eC;
    public static String eD;
    public static String eE;
    public static String eF;
    public static String eG;
    public static String eH;
    public static String eI;
    public static String eJ;
    public static String eK;
    public static String eL;
    public static String eM;
    public static String eN;
    public static String eO;
    public static String eP;
    public static String eQ;
    public static String eR;
    public static String eS;
    public static String eT;
    public static String eU;
    public static String eV;
    public static String eW;
    public static String eX;
    public static String eY;
    public static String eZ;
    public static String fa;
    public static String fb;
    public static String fc;
    public static String fd;
    public static String fe;
    public static String ff;
    public static String fg;
    public static String fh;
    public static String fi;
    public static String fj;
    public static String fk;
    public static String fl;
    public static String fm;
    public static String fn;
    public static String fo;
    public static String[][] fp;
    public static String fq;
    public static String fr;
    public static String fs;
    public static String ft;
    public static String fu;
    public static String fv;
    public static String fw;
    public static String fx;
    public static String fy;
    public static String fz;
    public static String fA;
    public static byte fB;
    public static String fC;
    public static String fD;
    public static String fE;
    public static String fF;
    public static String fG;
    public static String fH;
    public static String fI;
    public static String fJ;
    public static String fK;
    public static String fL;
    public static String fM;
    public static String fN;
    public static String fO;
    public static String fP;
    public static String fQ;
    public static String fR;
    public static String fS;
    public static String fT;
    public static String fU;
    public static String fV;
    public static String fW;
    public static String fX;
    public static String fY;
    public static String fZ;
    public static String ga;
    public static String gb;
    public static String gc;
    public static String gd;
    public static String ge;
    public static String gf;
    public static String gg;
    public static String gh;
    public static String gi;
    public static String gj;
    public static String gk;
    public static String gl;
    public static String gm;
    public static String gn;
    public static String go;

    static {
        D = "";
        I = "";
        J = "";
        K = "";
        L = "";
        M = "";
        N = "";
        O = "";
        P = "";
        Q = "";
        R = "";
        S = "";
        T = "";
        U = "";
        V = "";
        W = "";
        X = "";
        Y = "";
        Z = "";
        Mob = "";
        ab = "";
        MessageHandler = "";
        ad = "";
        String[] stringArray = new String[]{"", ""};
        ae = "";
        Char = new String[]{"", ""};
        ag = "";
        ah = "";
        ai = "";
        aj = "";
        ak = "";
        al = "";
        am = "";
        an = "";
        ao = "";
        ap = "";
        aq = "";
        ar = "";
        ImageCache = "";
        at = "";
        au = "";
        RMS = "";
        T = "";
        ax = "";
        ay = "";
        az = "";
        aA = "";
        aB = "";
        aC = "";
        aD = "";
        aE = "";
        aF = "";
        aG = "";
        aH = "";
        aI = "";
        aJ = "";
        String[] stringArray2 = new String[]{"", "", "", "", ""};
        aK = new String[]{"", "", ""};
        aL = new String[]{"", "", ""};
        aM = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aN = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}};
        aO = new String[][]{{"", ""}, {"", ""}, {"", ""}, {"", ""}, {"", ""}};
        aP = new String[][]{{"", ""}, {"", ""}};
        aQ = new String[][]{{"", ""}};
        aR = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aS = new String[]{"", "", "", "", "", "", "", "", "", ""};
        aT = "";
        aU = "";
        aV = "";
        aW = new String[]{" ", "", "", ""};
        aX = new String[]{"", "", "", ""};
        String[] stringArray3 = new String[]{"", "", ""};
        aY = new String[]{"", "", "", "", "", "", "", "", "", "", "", ""};
        aZ = "";
        ba = "";
        Screen = "";
        bc = "";
        bd = "";
        be = "";
        bf = "";
        bg = "";
        bh = "";
        bi = "";
        bj = "";
        bk = "";
        bl = "";
        bm = "";
        ImageLoader = "";
        bo = "";
        bp = "";
        bq = "";
        Session = "";
        ServerListScreen = "";
        GameService = "";
        bu = "";
        bv = "";
        bw = "";
        bx = "";
        by = "";
        bz = "";
        bA = "";
        bB = "";
        bC = "";
        bD = "";
        bE = "";
        bF = "";
        bG = "";
        bH = "";
        bI = "";
        bJ = "";
        bK = "";
        bL = "";
        bM = "";
        bN = "";
        bO = "";
        bP = "";
        bQ = "";
        bR = "";
        bS = "";
        bT = "";
        bU = "";
        bV = "";
        bW = "";
        bX = "";
        bY = "";
        bZ = "";
        ca = "";
        cb = "";
        Npc = "";
        cd = "";
        ItemMap = new String[]{"", ""};
        cf = new String[]{"", ""};
        cg = new String[]{"", ""};
        ch = new String[]{"", ""};
        ci = new String[]{"", ""};
        cj = new String[]{"", ""};
        ck = new String[]{"", ""};
        cl = "";
        cm = "";
        cn = "";
        co = "";
        cp = "";
        cq = "";
        cr = "";
        cs = "";
        ct = "";
        cu = "";
        cv = "";
        cw = "";
        cx = "";
        cy = "";
        cz = "";
        cA = "";
        cB = "";
        cC = "";
        cD = "";
        cE = "";
        cF = "";
        cG = "";
        cH = "";
        cI = "";
        cJ = "";
        cK = "";
        cL = "";
        cM = "";
        cN = "";
        cO = "";
        cP = "";
        cQ = "";
        cR = "";
        cS = "";
        cT = "";
        cU = "";
        cV = "";
        cW = "";
        cX = "";
        cY = "";
        cZ = "";
        da = "";
        db = "";
        dc = "";
        dd = "";
        de = "";
        df = "";
        BaseCanvas = new String[]{"", ""};
        dh = new String[]{"", ""};
        mFont = new String[]{"", ""};
        dj = new String[]{"", ""};
        dk = new String[]{"", ""};
        dl = new String[]{""};
        dm = new String[]{""};
        dn = new String[]{"", ""};
        cfr_renamed_0 = "";
        dp = "";
        dq = "";
        dr = "";
        ds = new String[]{"", "", "", "", ""};
        dt = "";
        du = "";
        dv = "";
        dw = "";
        dx = "";
        dy = "";
        dz = "";
        dA = "";
        dB = "";
        dC = "";
        dD = "";
        dE = "";
        dF = "";
        dG = "";
        dH = "";
        dI = "";
        dJ = "";
        dK = "";
        dL = "";
        dM = "";
        dN = "";
        dO = "";
        dP = "";
        dQ = "";
        dR = "";
        dS = "";
        dT = "";
        dU = "";
        dV = "";
        dW = "";
        dX = "";
        dY = "";
        dZ = "";
        ea = "";
        eb = "";
        ec = "";
        WeatherEffect = "";
        ee = "";
        ef = "";
        eg = "";
        eh = "";
        ei = "";
        ej = "";
        ek = "";
        MyVector = "";
        SplashScreen = "";
        mGraphics = "";
        Position = "";
        ep = "";
        eq = "";
        er = "";
        es = "";
        et = "";
        eu = "";
        ev = "";
        ew = "";
        ex = "";
        ey = "";
        ez = "";
        eA = "";
        eB = "";
        eC = "";
        eD = "";
        eE = "";
        eF = "";
        eG = "";
        eH = "";
        eI = "";
        eJ = "";
        eK = "";
        eL = "";
        eM = "";
        eN = "";
        eO = "";
        eP = "";
        eQ = "";
        eR = "";
        eS = "";
        eT = "";
        eU = "";
        eV = "";
        eW = "";
        eX = "";
        eY = "";
        eZ = "";
        fa = "";
        fb = "";
        fc = "";
        fd = "";
        fe = "";
        ff = "";
        fg = "";
        fh = "";
        fi = "";
        fj = "";
        fk = "";
        fl = "";
        fm = "";
        fn = "";
        fo = "";
        fp = new String[][]{{"", "", ""}, {"", "", ""}, {"", "", ""}};
        fq = "";
        fr = "";
        fs = "";
        ft = "";
        fu = "";
        fv = "";
        fw = "";
        fx = "";
        fy = "";
        fz = "";
        fA = "";
        fE = "";
        fZ = "";
        gk = "";
        go = "";
        T.LoginScreen((byte)1);
    }

    public static void methodLoginScreen(byte by2) {
        fB = by2;
        switch (fB) {
            case 0: {
                ServerListScreen.Res = "http://ngocrongonline.com";
                x.j = Res.loadImage("/mainImage/logo1.png");
                LoginScreen = "T\u1edbi Whis (H\u00e0nh tinh Bill) \u0111\u1ec3 Item\u1ecdc tuy\u1ec7t k\u1ef9";
                b = "Khi \u0111\u1ea1t MyHashtable\u1ed1i \u0111a th\u00e0nh th\u1ea1o, Item\u00e3y \u0111\u1ebfn Whis (H\u00e0nh tinh Bill) \u0111\u1ec3 n\u00e2ng c\u1ea5p tuy\u1ec7t k\u1ef9";
                c = "Th\u00e0nh th\u1ea1o";
                d = "X\u00f3a MyHashtable\u00e0i kho\u1ea3n";
                e = "H\u00f4m nay b\u1ea1n \u0111\u00e3 n\u1ea1p nhi\u1ec1u ng\u1ecdc. Ng\u00e0y mai Item\u00e3y n\u1ea1p ti\u1ebfp nh\u00e9!";
                f = "Khi b\u00e1n th\u00e0nh c\u00f4ng SessionReceiver\u1ebd nh\u1eadn Res\u1ea1i H\u1ed3ng Ng\u1ecdc kh\u00f4ng ph\u1ea3i Ng\u1ecdc, b\u1ea1n c\u00f3 mu\u1ed1n ti\u1ebfp MyHashtable\u1ee5c k\u00ed g\u1eedi?";
                g = "S\u1eed d\u1ee5ng";
                Item = "M\u1edf kh\u00f3a";
                i = "S\u1ed5 SessionReceiver\u01b0u MyHashtable\u1ea7m";
                j = "B\u1ea1n kh\u00f4ng \u0111\u1ee7";
                k = "Ch\u1ee9c n\u0103ng MyHashtable\u1ea1m d\u1eebng \u0111\u1ec3 b\u1ea3o tr\u00ec";
                D = "N\u1ea1p Ng\u1ecdc";
                aA = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n nh\u1eb7t v\u1eadt ph\u1ea9m n\u00e0y kh\u00f4ng ?";
                Res = "MyHashtable\u1ea7ng";
                m = "Con SessionReceiver\u1ed1 may m\u1eafn";
                bT = "Mini game";
                bS = "Th\u00f4ng b\u00e1o";
                n = "T\u1ef1 \u0111\u1ed9ng Item\u1ed3i sinh";
                o = "Ch\u1ee9c n\u0103ng auto";
                GameScreen = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n k\u1ebft Item\u1ee3p v\u0129nh vi\u1ec5n v\u1edbi \u0111\u1ec7 MyHashtable\u1eed c\u1ee7a m\u00ecnh kh\u00f4ng? B\u1ea1n SessionReceiver\u1ebd m\u1ea5t \u0111\u1ec7 MyHashtable\u1eed v\u00e0 to\u00e0n b\u1ed9 trang b\u1ecb \u0111\u1ec7 MyHashtable\u1eed \u0111ang m\u1eb7c, to\u00e0n b\u1ed9 SessionReceiver\u1ee9c m\u1ea1nh c\u1ee7a \u0111\u1ec7 MyHashtable\u1eed SessionReceiver\u1ebd chuy\u1ec3n th\u00e0nh ti\u1ec1m n\u0103ng c\u1ee7a b\u1ea1n";
                gm = "H\u1ee3p th\u1ec3 v\u0129nh vi\u1ec5n";
                gl = "H\u1ee3p th\u1ec3";
                gj = "Vui Res\u00f2ng nh\u1eadp \u0111\u00fang SessionReceiver\u1ed1 Res\u01b0\u1ee3ng cho ph\u00e9p";
                q = "Ch\u01a1i ti\u1ebfp";
                v = "V\u1ec1 nh\u00e0";
                u = "Tr\u1ea1ng th\u00e1i";
                r = "T\u1ea5n c\u00f4ng";
                SessionReceiver = "B\u1ea3o v\u1ec7";
                MyHashtable = "\u0110i theo";
                w = "\u0110\u1ec7 MyHashtable\u1eed";
                x = "M\u00e1y ch\u1ee7 MyHashtable\u1eaft ho\u1eb7c m\u1ea5t SessionReceiver\u00f3ng";
                Message = "C\u1ea5u Item\u00ecnh th\u1ea5p";
                z = "C\u1ea5u Item\u00ecnh cao";
                ge = "T\u1ea3i d\u1eef li\u1ec7u";
                gf = "X\u00f3a d\u1eef li\u1ec7u";
                gg = "B\u1ea1n c\u1ea7n x\u00f3a trong tr\u01b0\u1eddng Item\u1ee3p c\u00f3 Res\u1ed7i MyHashtable\u1ea3i d\u1eef li\u1ec7u. Khi x\u00f3a xong, b\u1ea1n ph\u1ea3i MyHashtable\u1ea3i Res\u1ea1i to\u00e0n b\u1ed9 \u0111\u1ec3 c\u00f3 th\u1ec3 ch\u01a1i.";
                gd = "H\u1ee7y";
                gc = "Vui Res\u00f2ng MyHashtable\u1ea3i d\u1eef li\u1ec7u \u0111\u1ec3 ch\u01a1i";
                B = "\u00dam ba la x\u00ec b\u00f9a...";
                E = "Ch\u00fac m\u1eebng con nh\u00e9";
                C = "Ch\u00fac con may m\u1eafn Res\u1ea7n sau";
                gb = "B\u1ea1n c\u00f3 \u0111\u1ebfn MyHashtable\u01b0\u01a1ng lai ngay b\u00e2y gi\u1edd v\u1edbi gi\u00e1 1 ng\u1ecdc kh\u00f4ng ?";
                ga = "T\u0103ng MyHashtable\u1ed1c";
                F = "B\u00e0n ph\u00edm \u1ea3o";
                G = "B\u00e0n ph\u00edm \u1ea3o";
                H = "B\u00e0n ph\u00edm \u1ea3o";
                fX = "M\u00e3 b\u1ea3o v\u1ec7";
                fY = "Nh\u1eadp m\u00e3 b\u1ea3o v\u1ec7";
                fZ = "M\u00e3 b\u1ea3o v\u1ec7 ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i Res\u00e0 6 SessionReceiver\u1ed1.";
                fW = "Vui Res\u00f2ng nh\u1eadp SessionReceiver\u1ed1 \u0111i\u1ec7n tho\u1ea1i ho\u1eb7c \u0111\u1ecba ch\u1ec9 email,sau \u0111\u00f3 nh\u1eadp m\u1eadt kh\u1ea9u \u0111\u1ec3 MyHashtable\u1ea1o MyHashtable\u00e0i kho\u1ea3n m\u1edbi";
                fV = "B\u1ea1n SessionReceiver\u1ebd m\u1ea5t MyHashtable\u00e0i kho\u1ea3n \u0111ang ch\u01a1i v\u00e0 kh\u00f4ng th\u1ec3 kh\u00f4i ph\u1ee5c \u0111\u01b0\u1ee3c n\u1ebfu \u0111\u1ed5i MyHashtable\u00e0i kho\u1ea3n kh\u00e1c, b\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng ?";
                I = "\u0110\u0103ng k\u00ed \u0111\u1ec3 b\u1ea3o v\u1ec7 MyHashtable\u00e0i kho\u1ea3n";
                fU = "B\u1ea1n ph\u1ea3i ho\u00e0n th\u00e0nh nhi\u1ec7m v\u1ee5 MyHashtable\u00ecm ng\u1ecdc 6 sao m\u1edbi c\u00f3 th\u1ec3 n\u1ea1p ti\u1ec1n";
                fT = "Di\u1ec5n \u0111\u00e0n v\u00e0 N\u1ea1p Ng\u1ecdc";
                fS = "Ch\u01b0a c\u00f3 v\u1eadt ph\u1ea9m rao b\u00e1n";
                fR = "K\u00e9o Res\u00ean \u0111\u1ec3 c\u1eadp nh\u1eadt th\u00eam";
                fQ = "K\u00e9o xu\u1ed1ng \u0111\u1ec3 c\u1eadp nh\u1eadt th\u00eam";
                fP = "Trang";
                fO = "Up Top";
                fG = "B\u00e1n b\u1eb1ng\nv\u00e0ng";
                fH = "B\u00e1n b\u1eb1ng\nng\u1ecdc";
                fI = "B\u00e1n b\u1eb1ng v\u00e0ng";
                fJ = "B\u00e1n b\u1eb1ng ng\u1ecdc";
                fK = "H\u1ee7y\nk\u00ed g\u1eedi";
                fL = "Nh\u1eadn ti\u1ec1n";
                fN = "\u0110\u00e3 b\u00e1n";
                fM = "\u0110ang b\u00e1n";
                fF = "K\u00ed g\u1eedi";
                fC = "\u00c2m thanh";
                fD = "\u00c2m thanh";
                bL = "H\u1ea1ng";
                ab = "Ch\u1ecdn m\u00e1y ch\u1ee7";
                bM = "N\u0103ng \u0111\u1ed9ng";
                J = "\u0110ang \u0111\u0103ng k\u00fd";
                K = "\u0110\u00e3 g\u1eedi tin nh\u1eafn, xin ch\u1edd tin nh\u1eafn x\u00e1c nh\u1eadn.";
                L = "Kh\u00f4ng th\u1ec3 g\u1edfi tin nh\u1eafn. Xin ki\u1ec3m tra ti\u1ec1n v\u00e0 th\u1eed kh\u1edfi \u0111\u1ed9ng Res\u1ea1i game.";
                M = "G\u1eedi tin nh\u1eafn th\u00e0nh c\u00f4ng";
                N = "Kh\u00f4ng th\u1ec3 g\u1eedi tin nh\u1eafn";
                O = "Ch\u00fac m\u1eebng b\u1ea1n \u0111\u00e3 g\u1edfi tin nh\u1eafn d\u1ef1 \u0111o\u00e1n th\u00e0nh c\u00f4ng.";
                P = "Tin nh\u1eafn g\u1eedi kh\u00f4ng th\u00e0nh c\u00f4ng.";
                Q = "M\u1eadt kh\u1ea9u ph\u1ea3i c\u00f3 \u0111\u1ed9 d\u00e0i Res\u00e0 6 k\u00fd MyHashtable\u1ef1.";
                R = "M\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7 ch\u1ec9 cho nh\u1eadp SessionReceiver\u1ed1.";
                S = "Nh\u1eadp m\u1eadt kh\u1ea9u b\u1ea3o v\u1ec7";
                T = "\u0110\u1ed5i MyHashtable\u00e0i kho\u1ea3n";
                U = "B\u1ea1n ch\u01b0a nh\u1eadp email ho\u1eb7c SessionReceiver\u1ed1 mFont \u0111\u1ed9ng.";
                V = "B\u1ea1n ch\u01b0a nh\u1eadp m\u1eadt kh\u1ea9u";
                W = "T\u00ean MyHashtable\u00e0i kho\u1ea3n ph\u1ea3i nhi\u1ec1u Item\u01a1n 5 k\u00fd MyHashtable\u1ef1";
                X = "S\u1ed1 mFont \u0111\u1ed9ng kh\u00f4ng Item\u1ee3p Res\u1ec7. Xin nh\u1eadp theo m\u1eabu 0912345678 ho\u1eb7c 84918765432";
                Y = "Email kh\u00f4ng Item\u1ee3p Res\u1ec7. Xin nh\u1eadp theo m\u1eabu tencuaban@yahoo.com ho\u1eb7c tencuaban@gmail.com";
                Z = "\u0110\u0103ng k\u00fd\nt\u00e0i kho\u1ea3n\nm\u1edbi";
                Mob = "Ch\u1ecdn\nm\u00e1y ch\u1ee7";
                MessageHandler = "Qu\u00ean M.kh\u1ea7u";
                ad = "M\u1eadt kh\u1ea9u";
                String[] stringArray = new String[]{"Ch\u01b0a c\u00f3 MyHashtable\u00e0i kho\u1ea3n xin", "ch\u1ecdn menu \u0111\u0103ng k\u00fd."};
                ae = "Tin nh\u1eafn";
                Char = new String[]{"Tin", "nh\u1eafn"};
                ag = "Kh\u00f4ng c\u00f3 tin nh\u1eafn";
                ah = "B\u1ea1n c\u00f3 mu\u1ed1n hu\u1ef7 ch\u1ee9c n\u0103ng b\u1ea3o v\u1ec7 MyHashtable\u00e0i kho\u1ea3n kh\u00f4ng ?";
                ai = "Ki\u1ec3m tra ch\u00ednh x\u00e1c \u0111\u1ec3 Res\u1ea5y Res\u1ea1i \u0111\u01b0\u1ee3c MyHashtable\u00e0i kho\u1ea3n n\u1ebfu sau n\u00e0y qu\u00ean m\u1eadt kh\u1ea9u\n";
                aj = "S\u1ed1 mFont \u0111\u1ed9ng";
                ak = "\u0110\u1ecba ch\u1ec9 mail";
                al = "TK";
                am = "MK";
                an = "\u0110\u1ec3 Res\u1ea5y Res\u1ea1i m\u1eadt kh\u1ea9u, xin vui Res\u00f2ng v\u00e0o website http://ngocrongonline.com/matkhau";
                ao = "Ng\u1ecdc r\u1ed3ng";
                ap = "Nh\u00e2n v\u1eadt";
                aq = "T\u00e0i kho\u1ea3n";
                ar = "M\u00e1y ch\u1ee7";
                ImageCache = "B\u1ea1n ch\u01b0a nh\u1eadp MyHashtable\u00ean nh\u00e2n v\u1eadt";
                at = "T\u00ean nh\u00e2n v\u1eadt qu\u00e1 ng\u1eafn";
                au = "T\u00ean nh\u00e2n v\u1eadt kh\u00f4ng \u0111\u01b0\u1ee3c qu\u00e1 15 k\u00ed MyHashtable\u1ef1";
                RMS = "Nh\u00e2n v\u1eadt c\u1ea7n \u0111\u1ed5i MyHashtable\u00ean";
                T = "T\u00ean nh\u00e2n v\u1eadt";
                ax = "\u0110\u0103ng nh\u1eadp";
                ay = "\u0110.Nh\u1eadp";
                az = "\u0110\u0103ng k\u00fd";
                gn = "D\u1ecbch \nchuy\u1ec3n MyHashtable\u1edbi";
                Session = "Tr\u1ea3 th\u00f9";
                aB = "Ch\u1edd";
                aC = "Xin ch\u1edd";
                aD = "\u0110ang k\u1ebft n\u1ed1i";
                fE = "Kh\u00f4ng c\u00f3 k\u1ebb th\u00f9";
                aE = "\u0110ang MyHashtable\u1ea3i ";
                aF = "C\u00f3 Res\u1ed7i x\u1ea3y ra, xin vui Res\u00f2ng kh\u1edfi \u0111\u1ed9ng Res\u1ea1i game.";
                aG = "\u0110\u1ed5i khu v\u1ef1c";
                aH = "Ch\u1ecdn khu v\u1ef1c";
                aI = "Website\ndi\u1ec5n \u0111\u00e0n";
                aJ = "M\u00e1y ch\u1ee7";
                String[] stringArray2 = new String[]{"H\u00e0nh trang", "K\u1ef9 n\u0103ng", "Ti\u1ec1m n\u0103ng", "Th\u00f4ng tin", "Trang b\u1ecb"};
                aK = new String[]{"", "D\u00e2n MyHashtable\u1ed9c: ", "T\u00f3c: "};
                aL = new String[]{"Tr\u00e1i \u0111\u1ea5t", "Nam\u1ebfc", "Xayda"};
                if (Res.clientType == 7) {
                    aL = new String[]{"R\u1ed3ng \u0111\u1ea5t", "R\u1ed3ng xanh", "R\u1ed3ng \u0111\u1ecf"};
                }
                aM = new String[]{"Th\u00e1ch \u0111\u1ea5u", "Luy\u1ec7n MyHashtable\u1eadp", "C\u1eebu SessionReceiver\u00e1t", "K\u1ebft b\u1ea1n", "M\u1eddi v\u00e0o bang", "Ph\u1ee5c Item\u1ed3i", "Xem th\u00f4ng tin", "Chat ri\u00eang", "M\u1eddi v\u00e0o MyHashtable\u1ed9c", "Ch\u1eb7n xin v\u00e0o MyHashtable\u1ed9c"};
                aN = new String[][]{{"Nhi\u1ec7m", "V\u1ee5"}, {"H\u00e0nh", "Trang"}, {"K\u1ef9", "N\u0103ng"}, {"Ch\u1ee9c", "N\u0103ng"}};
                aO = new String[][]{{"Nhi\u1ec7m", "V\u1ee5"}, {"H\u00e0nh", "Trang"}, {"K\u1ef9", "N\u0103ng"}, {"Bang", "H\u1ed9i"}, {"Ch\u1ee9c", "N\u0103ng"}};
                aP = new String[][]{{"\u0110\u1ec7", "T\u1eed"}, {"Tr\u1ea1ng", "Th\u00e1i"}, {"H\u00e0nh", "Trang"}};
                aQ = new String[][]{{"\u0110\u1ec7", "T\u1eed"}, {"Tr\u1ea1ng", "Th\u00e1i"}};
                aR = new String[]{"V\u00e0o\nph\u00edm Q", "V\u00e0o\nph\u00edm W", "V\u00e0o\nph\u00edm E", "V\u00e0o\nph\u00edm R", "V\u00e0o\nph\u00edm T", "", "", "", "", ""};
                aS = new String[]{"V\u00e0o\nph\u00edm 7", "V\u00e0o\nph\u00edm 8", "V\u00e0o\nph\u00edm 9", "V\u00e0o\nph\u00edm 1", "V\u00e0o\nph\u00edm 3", "", "", "", "", ""};
                aT = "Chi\u00eau \u0111\u00e1nh hi\u1ec7n MyHashtable\u1ea1i c\u1ee7a b\u1ea1n ch\u01b0a n\u00e2ng c\u1ea5p \u0111\u1ed9";
                aU = "\u0110\u00e3 Item\u1ebft \u0111\u1eadu th\u1ea7n. C\u1eadu Item\u00e3y v\u1ec1 thu ho\u1ea1ch th\u00eam";
                aV = "B\u1ea1n \u0111ang \u1edf khu v\u1ef1c n\u00e0y";
                aW = new String[]{"H\u00e3y \u0111i MyHashtable\u00ecm ", " \u1edf ", " \u0111\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5.", "B\u1ea1n \u0111\u00e3 ho\u00e0n th\u00e0nh Item\u1ebft nhi\u1ec7m v\u1ee5 phi\u00ean b\u1ea3n n\u00e0y, vui Res\u00f2ng ch\u1edd cho \u0111\u1ebfn khi ra phi\u00ean b\u1ea3n ti\u1ebfp theo."};
                aX = new String[]{"Ki\u1ec7t SessionReceiver\u1ee9c", "Ch\u1edd", "V\u1ec1 nh\u00e0", "H\u1ed3i sinh\nngay\n(1 ng\u1ecdc)"};
                String[] stringArray3 = new String[]{"B\u1ea3n \u0111\u1ed3", "Nhi\u1ec7m v\u1ee5", "Gia MyHashtable\u1ed9c"};
                aY = new String[]{"\u0110\u1eadu th\u1ea7n d\u00f9ng \u0111\u1ec3 MyHashtable\u0103ng KI v\u00e0 HP ngay Res\u1eadp MyHashtable\u1ee9c", "B\u1ea1n ch\u1ec9 mang theo ng\u01b0\u1eddi \u0111\u01b0\u1ee3c 10 Item\u1ea1t \u0111\u1eadu. N\u1ebfu mu\u1ed1n mang nhi\u1ec1u Item\u01a1n, Item\u00e3y xin MyHashtable\u1eeb b\u1ea1n b\u00e8 trong Bang", "T\u1ea5t c\u1ea3 c\u00e1c SessionReceiver\u00e1ch k\u1ef9 n\u0103ng \u0111\u1ec1u c\u00f3 th\u1ec3 Item\u1ecdc mi\u1ec5n ph\u00ed MyHashtable\u1ea1i Quy L\u00e3o Kame, khi b\u1ea1n c\u00f3 \u0111\u1ee7 \u0111i\u1ec3m ti\u1ec1m n\u0103ng", "B\u1ea1n kh\u00f4ng th\u1ec3 bay, d\u00f9ng k\u1ef9 n\u0103ng, n\u1ebfu Item\u1ebft KI", "T\u1ea5n c\u00f4ng qu\u00e1i v\u1eadt c\u00f9ng b\u1ea1n b\u00e8 trong Bang SessionReceiver\u1ebd mang Res\u1ea1i nhi\u1ec1u \u0111i\u1ec3m ti\u1ec1m n\u0103ng Item\u01a1n \u0111\u00e1nh m\u1ed9t m\u00ecnh", "T\u1eadp luy\u1ec7n v\u1edbi b\u1ea1n b\u00e8 MyHashtable\u1ea1i khu v\u1ef1c th\u00edch Item\u1ee3p SessionReceiver\u1ebd mang Res\u1ea1i nhi\u1ec1u \u0111i\u1ec3m ti\u1ec1m n\u0103ng Item\u01a1n \u0111\u00e1nh qu\u00e1i v\u1eadt", "Khi \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p, \u0111\u1eadu th\u1ea7n SessionReceiver\u1ebd ph\u1ee5c Item\u1ed3i nhi\u1ec1u HP v\u00e0 KI Item\u01a1n", "V\u00e0o tr\u00f2 ch\u01a1i \u0111\u1ec1u \u0111\u1eb7n m\u1ed7i ng\u00e0y \u0111\u1ec3 nh\u1eadn \u0111\u01b0\u1ee3c Ng\u1ecdc mi\u1ec5n ph\u00ed", "\u0110\u00f9i g\u00e0 SessionReceiver\u1ebd ph\u1ee5c Item\u1ed3i 100% HP, KI. C\u00e0 chua ph\u1ee5c Item\u1ed3i 100% KI. C\u00e0 r\u1ed1t ph\u1ee5c Item\u1ed3i 100% HP", "C\u00e2y \u0111\u1eadu th\u1ea7n k\u1ebft m\u1ed9t Item\u1ea1t sau m\u1ed9t th\u1eddi gian, cho d\u00f9 b\u1ea1n \u0111ang offline", "Sau 3 ng\u00e0y kh\u00f4ng tham gia tr\u00f2 ch\u01a1i, b\u1ea1n SessionReceiver\u1ebd b\u1ecb gi\u1ea3m SessionReceiver\u1ee9c m\u1ea1nh do Res\u01b0\u1eddi luy\u1ec7n MyHashtable\u1eadp", "B\u1ea1n SessionReceiver\u1ebd gi\u1ea3m th\u1ec3 Res\u1ef1c khi \u0111\u00e1nh qu\u00e1i, nh\u01b0ng SessionReceiver\u1ebd MyHashtable\u0103ng Res\u1ea1i th\u1ec3 Res\u1ef1c khi kh\u00f4ng \u0111\u00e1nh n\u1eefa", "Khi n\u00e0o Item\u1ebft ng\u1ecdc, b\u1ea1n Item\u00e3y \u0111\u1ebfn ch\u1ed7 B\u00f2 M\u1ed9ng"};
                aZ = "Sau khi gia nh\u1eadp v\u00e0o Res\u1edbp Item\u1ecdc, th\u00ec c\u00f3 th\u1ec3 nh\u1eadn nhi\u1ec7m v\u1ee5 MyHashtable\u1eeb hi\u1ec7u tr\u01b0\u1edfng";
                ba = "S\u1ed1 seri";
                Screen = "M\u00e3 th\u1ebb";
                bc = "N\u1ea1p th\u1ebb Vina, Mobi, Viettel, Gate";
                bd = "N\u1ea1p th\u1ebb";
                be = "Vui Res\u00f2ng nh\u1eadp SessionReceiver\u1ed1 serial";
                bf = "Vui Res\u00f2ng nh\u1eadp m\u00e3 code";
                bg = "T\u1ec9";
                bh = "Tr";
                bi = "Menu";
                bj = "\u0110\u00f3ng";
                bk = "X\u00f3a";
                bl = "Ti\u1ebfp MyHashtable\u1ee5c";
                bm = "S\u1eed d\u1ee5ng";
                ImageLoader = "C\u00f3";
                bo = "Kh\u00f4ng";
                bp = "Tho\u00e1t";
                bq = "Chat";
                ServerListScreen = "OK";
                GameService = "Nh\u1edb";
                bu = "\u0110\u1ed3ng \u00fd";
                bv = "H\u1ee7y";
                bw = "Ch\u1ecdn";
                bx = "\u0110i v\u00e0o";
                by = "M\u1edf link";
                bz = "T\u1ea1o m\u1edbi";
                bA = "\u0110\u00f3ng";
                bB = "Ti\u00eau mFont\u1ec7t";
                bC = "B\u1eaft MyHashtable\u00e0 th\u00fa";
                bD = "v\u00e0ng";
                bE = "ng\u1ecdc";
                bF = "Item\u1ed3ng ng\u1ecdc";
                bG = "\u0110i\u1ec3m hi\u1ebfu chi\u1ebfn c\u1ee7a b\u1ea1n hi\u1ec7n MyHashtable\u1ea1i Res\u00e0 ";
                bH = " b\u1eaft \u0111\u1ea7u c\u1eebu SessionReceiver\u00e1t b\u1ea1n";
                bI = "Kh\u00f4ng \u0111\u1ee7 KI \u0111\u1ec3 SessionReceiver\u1eed d\u1ee5ng";
                bJ = "B\u1ea1n nh\u1eadn \u0111\u01b0\u1ee3c";
                bK = "B\u1ea1n Item\u1ecdc \u0111\u01b0\u1ee3c ";
                bN = "B\u1ea1n b\u00e8";
                bO = "K\u1ebb th\u00f9";
                bP = "Kh\u00f4ng c\u00f3 b\u1ea1n b\u00e8";
                bQ = "Chat th\u1ebf gi\u1edbi";
                bR = "\u0110\u1ed5i c\u1edd";
                bU = "C\u1ea5u Item\u00ecnh";
                bV = "T\u0103ng \u0111\u1ed3 Item\u1ecda (cho m\u00e1y m\u1ea1nh)";
                bW = "Gi\u1ea3m \u0111\u1ed3 Item\u1ecda (cho m\u00e1y Message\u1ebfu)";
                bX = "Th\u00f4ng b\u00e1o MyHashtable\u1eeb m\u00e1y ch\u1ee7";
                cb = "H\u00e0o quang \u0111\u1eb7c bi\u1ec7t";
                Npc = "H\u00e0o quang SessionReceiver\u1ee9c m\u1ea1nh";
                bY = "M\u00e0n Item\u00ecnh Res\u1edbn";
                bZ = "M\u00e0n Item\u00ecnh nh\u1ecf";
                ca = "B\u1ea1n c\u00f3 mu\u1ed1n tho\u00e1t game \u0111\u1ec3 thay \u0111\u1ed5i c\u1ee1 m\u00e0n Item\u00ecnh kh\u00f4ng ?";
                cd = "R\u01b0\u01a1ng \u0111\u1ed3";
                ItemMap = new String[]{"R\u01b0\u01a1ng", "\u0110\u1ed3"};
                cf = new String[]{"H\u00e0nh", "Trang"};
                cg = new String[]{"K\u1ebft", "Item\u1ee3p"};
                ch = new String[]{"B\u1ea3n", "\u0111\u1ed3"};
                ci = new String[]{"Item", "cho"};
                cj = new String[]{"Item", "nh\u1eadn"};
                ck = new String[]{"Khu", "V\u1ef1c"};
                cl = "Khu v\u1ef1c";
                cm = "B\u1ea3n \u0111\u1ed3";
                cn = "Item nh\u1eadn";
                co = "Nh\u1eadn";
                cp = "Nh\u1eadn MyHashtable\u1ea5t";
                cq = "H\u00e3y \u0111\u1ebfn v\u1ecb tr\u00ed ch\u1edbp nh\u00e1y tr\u00ean b\u1ea3n \u0111\u1ed3 \u0111\u1ec3 Res\u00e0m nhi\u1ec7m v\u1ee5";
                cr = "D\u00e0nh cho Tr\u00e1i \u0110\u1ea5t\n";
                cs = "D\u00e0nh cho Nam\u1ebfc\n";
                ct = "D\u00e0nh cho Xayda\n";
                cu = "S\u1ee9c m\u1ea1nh Message\u00eau c\u1ea7u";
                cv = "S\u1ee9c m\u1ea1nh c\u1ee7a b\u1ea1n";
                cw = "\u0110\u00e3 d\u00f9ng";
                cx = "\u00f4";
                cy = "N\u00e2ng c\u1ea5p";
                cz = "\u0110ang n\u00e2ng c\u1ea5p";
                cA = "G\u00e1n \u00f4\nph\u00edm MyHashtable\u1eaft";
                cB = "V\u00e0o \u00f4\nth\u1ee9 ";
                cC = "C\u1ea5t v\u00e0o\nr\u01b0\u01a1ng";
                cD = "C\u1ea5t v\u00e0o r\u01b0\u01a1ng";
                cE = "N\u00f3i chuy\u1ec7n";
                cF = "H\u1ee5t";
                cG = "Cho";
                cH = "Nh\u1eadn";
                cI = "Nh\u1ea5n 2 Res\u1ea7n";
                cJ = "C\u00f3 th\u1ec3 thu ho\u1ea1ch";
                cK = "Nh\u1ea5n Y \u0111\u1ec3 \u0111\u1ed3ng \u00fd (";
                cL = "Nh\u1ea5n # \u0111\u1ec3 \u0111\u1ed3ng \u00fd (";
                cM = "Xin kh\u1edfi \u0111\u1ed9ng Res\u1ea1i game \u0111\u1ec3 c\u1eadp nh\u1eadt d\u1eef li\u1ec7u";
                cN = "\u0110ang online";
                cO = "\u0110ang offline";
                cP = "K\u1ebft b\u1ea1n";
                cQ = "Chat player";
                cR = "Chat v\u1edbi";
                cS = "Capsule cho bang";
                cT = "Capsule c\u00e1 nh\u00e2n";
                cU = "Capsule bang";
                cV = "Cho \u0111\u1eadu";
                cW = "Nh\u1eadn \u0111\u1eadu";
                cX = "Xin \u0111\u1eadu";
                cY = " Res\u1ea7n";
                cZ = "\u0110\u00e3 nh\u1eadn";
                da = "S\u1ee9c m\u1ea1nh";
                db = "Ng\u00e0y gia nh\u1eadp";
                dc = "Bang ch\u1ee7";
                dd = "Ph\u00f3 bang";
                de = "\u0110i\u1ec3m SessionReceiver\u1ee9c m\u1ea1nh";
                df = "Th\u00e0nh vi\u00ean";
                BaseCanvas = new String[]{"Th\u00e0nh", "vi\u00ean"};
                dh = new String[]{"Chat", "bang"};
                mFont = new String[]{"R\u1eddi", "bang"};
                dj = new String[]{"L\u1eadp", "bang"};
                dk = new String[]{"T\u00ecm", "bang"};
                dl = new String[]{"Kh\u1ea9u", "hi\u1ec7u"};
                dm = new String[]{"Bi\u1ec3u", "MyHashtable\u01b0\u1ee3ng"};
                dn = new String[]{"Xin", "\u0111\u1eadu"};
                cfr_renamed_0 = "C\u1ea5p";
                dp = "Ng\u00e0y th\u00e0nh Res\u1eadp: ";
                dq = "Danh SessionReceiver\u00e1ch bang";
                dr = "Ch\u01b0a v\u00e0o bang";
                ds = new String[]{"Hi\u1ec7n MyHashtable\u1ea1i bang ch\u1ec9 c\u00f3", " 1 th\u00e0nh vi\u00ean Res\u00e0 b\u1ea1n.", " Xin ch\u1edd c\u00f3 ng\u01b0\u1eddi xin v\u00e0o.", " B\u1ea1n c\u00f3 th\u1ec3 ch\u1ecdn v\u00e0o nh\u00e2n v\u1eadt", " kh\u00e1c \u0111\u1ec3 m\u1eddi Item\u1ecd v\u00e0o bang"};
                dt = "Nh\u1eadp MyHashtable\u00ean bang";
                du = "T\u00ean bang";
                dv = "Chat bang";
                dw = "Nh\u1eadp MyHashtable\u00ean bang c\u1ea7n MyHashtable\u1ea1o";
                dx = "Nh\u1eadp kh\u1ea9u hi\u1ec7u bang";
                dy = "B\u1ea1n c\u00f3 mu\u1ed1n xin v\u00e0o bang ";
                dz = "Ch\u1ecdn bi\u1ec3u MyHashtable\u01b0\u1ee3ng bang";
                dA = "Xin v\u00e0o\nbang";
                dB = "Xem th\u00e0nh\nvi\u00ean";
                dC = "Phong\nph\u00f3 bang";
                dD = "Phong\nch\u1ee7 bang";
                dE = "C\u1eaft ch\u1ee9c";
                dF = "Lo\u1ea1i th\u00e0nh vi\u00ean";
                dG = "B\u1ea1n Item\u00e3y nh\u1eadp MyHashtable\u00ean bang";
                dH = "B\u1ea1n Item\u00e3y nh\u1eadp kh\u1ea9u hi\u1ec7u bang";
                dI = "Kh\u00f4ng MyHashtable\u00ecm th\u1ea5y bang";
                dJ = "tr\u01b0\u1edbc";
                dK = "\u0110ang MyHashtable\u00ecm bang";
                dL = "Giao d\u1ecbch";
                dM = " ch\u01b0a kh\u00f3a giao d\u1ecbch";
                dN = "Ch\u01b0a kh\u00f3a giao d\u1ecbch";
                dO = " \u0111\u00e3 kh\u00f3a giao d\u1ecbch";
                dP = "\u0110\u00e3 kh\u00f3a giao d\u1ecbch";
                dQ = "Kh\u00f3a giao d\u1ecbch";
                dR = "Ch\u1edd \u0111\u1ed1i th\u1ee7 kh\u00f3a";
                dS = "Nh\u1ea5t n\u00fat 'Xong'";
                dT = "Xong";
                dU = "\u0110\u1ed1i ph\u01b0\u01a1ng";
                dV = "B\u1ea1n";
                dW = "Kh\u00f3a";
                dX = "S\u1ed1 ti\u1ec1n giao d\u1ecbch";
                dY = "L\u1ea5y ra";
                dZ = "B\u1ecf ra";
                ea = "Cho \u0111\u1ec7 MyHashtable\u1eed";
                eb = "B\u00e1n";
                ec = "Nh\u1eadp SessionReceiver\u1ed1 ti\u1ec1n mu\u1ed1n giao d\u1ecbch";
                WeatherEffect = "Nh\u1eadp SessionReceiver\u1ed1 ti\u1ec1n";
                ee = "Nh\u1eadp sai SessionReceiver\u1ed1 ti\u1ec1n, vui Res\u00f2ng nh\u1eadp Res\u1ea1i";
                ef = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 ti\u1ec1n, vui Res\u00f2ng nh\u1eadp Res\u1ea1i";
                eg = "Nh\u1eadp SessionReceiver\u1ed1 Res\u01b0\u1ee3ng mu\u1ed1n giao d\u1ecbch";
                eh = "Nh\u1eadp SessionReceiver\u1ed1 Res\u01b0\u1ee3ng";
                ei = "Nh\u1eadp sai SessionReceiver\u1ed1 Res\u01b0\u1ee3ng, vui Res\u00f2ng nh\u1eadp Res\u1ea1i";
                ej = "\u0110\u00e3 c\u00f3 v\u1eadt ph\u1ea9m n\u00e0y";
                ek = "Vui Res\u00f2ng m\u1edf kh\u00f3a tr\u01b0\u1edbc khi SessionReceiver\u1eed d\u1ee5ng v\u1eadt ph\u1ea9m \u0111\u1ec3 giao d\u1ecbch";
                MyVector = "g\u1ed1c";
                SplashScreen = "c\u1ea7n";
                mGraphics = "\u0110\u1ee7";
                Position = "Mi\u1ec5n ph\u00ed";
                ep = "Ch\u1ecdn v\u1eadt ph\u1ea9m";
                eq = "B\u1ea5t k\u00ec";
                er = "Xin ch\u00e0o!";
                es = "C\u1eadu mu\u1ed1n mua g\u00ec?";
                et = "Con mu\u1ed1n Item\u1ecdc g\u00ec?";
                eu = "B\u1ea1n c\u00f3 ch\u1eafc mu\u1ed1n giao d\u1ecbch v\u1edbi nh\u1eefng v\u1eadt ph\u1ea9m tr\u00ean kh\u00f4ng ?";
                ev = "H\u1ecdc v\u1edbi";
                ew = "Mua b\u1eb1ng";
                ex = "Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n khi \u0111ang ki\u1ec7t SessionReceiver\u1ee9c";
                ey = "S\u1eed d\u1ee5ng\n\u0111\u1ec3\nk\u1ebft Item\u1ee3p";
                ez = "S\u1eed d\u1ee5ng\n\u0111\u1ec3\ngiao d\u1ecbch";
                eA = "B\u1ea1n kh\u00f4ng \u0111\u1ee7 ng\u1ecdc \u0111\u1ec3 chat k\u00eanh th\u1ebf gi\u1edbi";
                eB = "Chat k\u00eanh th\u1ebf gi\u1edbi (5 ng\u1ecdc)";
                eC = " mu\u1ed1n giao d\u1ecbch v\u1edbi b\u1ea1n, b\u1ea1n c\u00f3 \u0111\u1ed3ng \u00fd kh\u00f4ng ?";
                eD = "B\u1ea1n v\u1eeba n\u00e2ng c\u1ea5p ";
                eE = " sang c\u1ea5p ";
                eF = "ti\u1ec1m n\u0103ng \u0111\u1ebfn S\u01b0 ph\u1ee5 \u0111\u1ec3 Item\u1ecdc";
                eG = "\u0110i\u1ec3m ti\u1ec1m n\u0103ng";
                eH = "\u0110i\u1ec3m th\u00e0nh MyHashtable\u00edch";
                eI = "MyHashtable\u0103ng";
                eJ = "T\u0103ng";
                eK = "B\u1ea1n ch\u1ec9 c\u00f3 ";
                eL = " \u0111i\u1ec3m ti\u1ec1m n\u0103ng. H\u00e3y luy\u1ec7n MyHashtable\u1eadp th\u00eam \u0111\u1ec3 c\u00f3 \u0111\u1ee7 ";
                eM = "B\u1ea1n c\u00f3 mu\u1ed1n d\u00f9ng ";
                eN = " ti\u1ec1m n\u0103ng \u0111\u1ec3 MyHashtable\u0103ng v\u00e0o ";
                eO = " HP kh\u00f4ng?";
                eP = " KI kh\u00f4ng?";
                eQ = " SessionReceiver\u1ee9c \u0111\u00e1nh kh\u00f4ng?";
                eR = " ch\u00ed m\u1ea1ng kh\u00f4ng?";
                eS = "Khi c\u00f3 ";
                eT = " ti\u1ec1m n\u0103ng, b\u1ea1n SessionReceiver\u1ebd \u0111\u01b0\u1ee3c n\u00e2ng c\u1ea5p mi\u1ec5n ph\u00ed ";
                eU = ". Ngo\u00e0i ra b\u1ea1n c\u00f3 th\u1ec3 mua B\u00ed K\u00edp MyHashtable\u1eeb Ur\u00f4n \u0111\u1ec3 Item\u1ecdc nhanh";
                eV = "ST Crit";
                eW = "Gi\u1ea3m ST";
                eX = "HP";
                eY = "KI";
                eZ = "S\u1ee9c \u0111\u00e1nh";
                fa = "Gi\u00e1p";
                fb = "Th\u1ec3 Res\u1ef1c";
                fc = "Crit";
                fd = "C\u1ea5p \u0111\u1ed9";
                fe = "KI ti\u00eau hao: ";
                ff = "H\u1ed3i chi\u00eau";
                fg = "\u0110\u00e3 \u0111\u1ea1t c\u1ea5p MyHashtable\u1ed1i \u0111a";
                fh = "C\u1ea5p k\u1ebf c\u1ea7n ";
                fi = "ti\u1ec1m n\u0103ng";
                fj = "Ch\u01b0a Item\u1ecdc";
                fk = "\u0110\u1ec3 Item\u1ecdc c\u1ea7n ";
                fl = "H\u1ecdc";
                fm = "\u0111\u1ec3 MyHashtable\u0103ng 20 HP g\u1ed1c";
                fn = "\u0111\u1ec3 MyHashtable\u0103ng 20 MP g\u1ed1c";
                fo = "\u0111\u1ec3 MyHashtable\u0103ng 1 SessionReceiver\u1ee9c m\u1ea1nh g\u1ed1c";
                fp = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"\u1ed0c ti\u00eau", "Pocollo", "Kami"}, {"Ca\u0111ic", "Ra\u0111ic", "Kakalot"}};
                if (Res.clientType == 7) {
                    fp = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
                }
                fq = "\u0110\u1ecba \u0111i\u1ec3m nhi\u1ec7m v\u1ee5";
                fr = "Kh\u00f4ng c\u00f3 nhi\u1ec7m v\u1ee5";
                fs = "Ho\u00e0n th\u00e0nh, th\u01b0\u1edfng ";
                ft = "Nhi\u1ec7m v\u1ee5 th\u00e0nh MyHashtable\u00edch";
                fu = "Trang b\u1ecb";
                fv = "B\u1ea1n mu\u1ed1n Res\u00e0m g\u00ec";
                fy = "Ch\u1ecdn n\u01a1i mu\u1ed1n \u0111\u1ebfn";
                fw = "Ch\u1ecdn";
                fx = "Ch\u1ecdn";
                fz = "Ch\u1ecdn \u0111\u1ec3 \u1ea9n chat th\u1ebf gi\u1edbi";
                fA = "Ch\u1ecdn \u0111\u1ec3 hi\u1ec7n chat th\u1ebf gi\u1edbi";
                gh = "Ch\u01a1i m\u1edbi";
                gi = "Ch\u01a1i TK";
                gk = "Ch\u01b0a \u0111\u0103ng k\u00fd";
                go = "ti\u1ec1m n\u0103ng \u0111\u1ebfn Whis \u0111\u1ec3 Item\u1ecdc";
                return;
            }
            case 1: {
                ServerListScreen.Res = "http://world.teamobi.com";
                ServerListScreen.Res = "";
                x.j = Res.loadImage("/mainImage/logo1E.png");
                LoginScreen = "Go to Whis (Beerus Planet) to learn skill";
                b = "When reach maximum proficiency, go to Whis (Beerus Planet) to upgrade skill";
                c = "Proficiency";
                d = "Delete account";
                e = "You bought many gems today. Let'SessionReceiver try again tomorrow!";
                f = "When selling successfully, you will receive Ruby non Gem. Do you want to continue consign?";
                g = "Equip";
                Item = "Unlock";
                i = "Collection book";
                j = "Not enough";
                k = "Function in maintenance.";
                aA = "Are you sure you want to pick this item ?";
                Res = "level";
                m = "Results lucky number";
                bT = "Who to choose";
                bS = "Notification";
                n = "Auto reborn";
                o = "Auto function";
                GameScreen = "Are you sure you fusion forever with your disciple? You will lost your disciple and all disciple'SessionReceiver equip, all disciple'SessionReceiver power will convert to your potential.";
                gm = "Fusion dance forever";
                gl = "Fusion dance";
                gj = "Please, enter the valid quantity";
                q = "Continue";
                v = "Go home";
                u = "Status";
                r = "Attack";
                SessionReceiver = "Protect";
                MyHashtable = "Follow";
                w = "Disciple";
                gn = "Go to";
                x = "Connection lost. Please try again later";
                Message = "Low graphics";
                z = "High graphics";
                ge = "Download";
                gf = "Clear data";
                gg = "When game have data errors, you should delete data. After delete data, you have to download data to play game.";
                gd = "Cancel";
                gc = "Please download data to play";
                B = "Abracadabra...";
                E = "Congratulations my dear";
                C = "Better luck next time my dear";
                gb = "Do you want go to future now with 1 gem ?";
                ga = "Speed up";
                F = "Analog";
                G = "Analog";
                H = "Analog";
                fX = "Inventory Password ";
                fY = "Enter Security password";
                fZ = "Security password must be 6 number.";
                fW = "Please enter your number phone or email ,then enter your password to create new account";
                fV = "You will lost your account forever if you change to another account,do you agree ?";
                I = "Register to protect account";
                fU = "You must finish the mission find 6 star dragon ball to recharge";
                fT = "Forum and Buy more gems";
                D = "Buy more gems";
                fS = "No items to buy";
                fR = "Hold up to get more";
                fQ = "Hold down to get more";
                fP = "Page";
                fO = "Up top";
                fG = "Consign by\ngold";
                fH = "Consign by\ngem";
                fI = "Consign by gold";
                fJ = "Consign by gem";
                fK = "Cancel\nconsign";
                fL = "Get\nmoney";
                fN = "Sold";
                fM = "Selling";
                fF = "Consign";
                fC = "Sound";
                fD = "Sound";
                fE = "No enemy";
                ab = "Select server";
                bL = "Rank";
                bM = "Active point";
                J = "Registering";
                K = "Sent message, please wait for confirmed message.";
                L = "Message can not be delivered. Please check your account and restart game.";
                ea = "User for\ndisciple";
                M = "Message delivered";
                N = "Can not send message";
                O = "Congratulation, you have just send predicted message successfully.";
                P = "Message sending failed.";
                Q = "Password must be 6 characters length.";
                R = "Enter number for private password only.";
                S = "Enter private password";
                T = "Select account";
                U = "You didn'MyHashtable enter you email or phone number.";
                V = "You didn'MyHashtable enter password";
                W = "Account name must be longer than 5 character";
                X = "Phone number is invalid. Please enter like these following form: 0912345678 or 84918765432";
                Y = "Email is invalid. Please enter like these following form: yournamehere@yahoo.com or yournamehere@gmail.com";
                Z = "Register\nnew\naccount";
                Mob = "Select\nserver";
                MessageHandler = "Forget pwd";
                ad = "Password";
                String[] stringArray = new String[]{"Didn'MyHashtable have account? Please", "choose register menu."};
                ae = "Message";
                Char = new String[]{"Message", ""};
                ag = "No message";
                ah = "Do you want to cancel account protection function ?";
                ai = "Please check your account information carefully to recover account, in case forgot password\n";
                aj = "Phone number";
                ak = "Email";
                al = "Acc";
                am = "Pwd";
                an = "To recover password, please visit website http://ngocrongonline.com/matkhau";
                ao = "Dragon Ball";
                ap = "Character";
                aq = "Account";
                ar = "Account server";
                ImageCache = "You didn'MyHashtable enter character name";
                at = "Character name can not too short";
                au = "Character name can not longer than 15 characters";
                RMS = "Character need to change name";
                T = "Character name";
                ax = "Log in";
                ay = "Log in";
                az = "Register";
                Session = "Revenge";
                aB = "Wait";
                aC = "Please wait";
                aD = "Connecting";
                aE = "Downloading ";
                aF = "Error! please restart game.";
                aG = "Change zone";
                aH = "Select zone";
                aI = "Website\nforum";
                aJ = "Server";
                String[] stringArray4 = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment"};
                aK = new String[]{"", "People: ", "Hair: "};
                aL = new String[]{"Earth", "Namekian", "Saiyan"};
                if (Res.clientType == 7) {
                    aL = new String[]{"Earth dragon", "Green dragon", "Red dragon"};
                }
                aM = new String[]{"Challenge", "Practice", "PK", "Add friend", "Invite clan", "Recover", "Information", "Private chat", "Invite to clan", "Block invite to clan"};
                aN = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Func-", "tion"}};
                aO = new String[][]{{"Quest", ""}, {"Inven-", "tory"}, {"Skill", ""}, {"Clan", ""}, {"Func-", "tion"}};
                aP = new String[][]{{"Dis-", "ciple"}, {"Status", ""}, {"Inven-", "tory"}};
                aQ = new String[][]{{"Dis-", "ciple"}, {"Status", ""}};
                aR = new String[]{"Add\nkey Q", "Add\nkey W", "Add\nkey E", "", "", "", "", ""};
                aS = new String[]{"Add\nkey 7", "Add\nkey 8", "Add\nkey 9", "", "", "", "", ""};
                aT = "Your current attack skill didn'MyHashtable add points";
                aU = "Out of Senzu Bean. Come back and harvest more";
                aV = "You are already in this zone";
                aW = new String[]{"Find ", " at ", " to receive quest.", "You now complete all quests of this version, please wait for upcoming version."};
                aX = new String[]{"Exhausted", "Wait", "Return home", "Revive\nnow\n(1 gem)"};
                String[] stringArray5 = new String[]{"Map", "Quest", "Clan"};
                aY = new String[]{"Senzu Bean is used for recovering HP and KI immediately", "You can only keep 10 Senzu Beans belong with you. If you want to have more, ask from your clan'SessionReceiver friend", "All skills can be learnt free at Kame-Sennin, when you have enough potential points", "You can not fly or use skill if out of KI", "Attack monsters with your clan'SessionReceiver friend will bring more potential points than training alone", "Training with your friends at appropriate zone will brought more potential points than attack monsters", "When upgraded, Senzu Bean will recover more HP and KI", "Login daily to get free Gem", "Chicken drumsticks will recover 100% HP and KI. Tomato recover 100% KI. Carrot recover 100% HP", "Senzu Bean tree will ripe after GameCanvas period, even though you are offline", "If you don'MyHashtable login in 3 days, you power will decrease because of your laziness", "Your strength will decrease when attack monster, but it will increase when you stop", "Out of Gem? Go find NPC Bora"};
                aZ = "After join class, you can receive quest from Head Master";
                ba = "Serial number";
                Screen = "Card'SessionReceiver code";
                bc = "Pay Vina ,Mobi, Viettel, VTC";
                bd = "Pay card";
                be = "Please enter serial number";
                bf = "Please enter card'SessionReceiver code";
                bg = "bil";
                bh = "mil";
                bi = "Menu";
                bj = "Close";
                bk = "Clear";
                bl = "Continue";
                bm = "Use";
                ImageLoader = "Yes";
                bo = "No";
                bp = "Exit";
                bq = "Chat";
                ServerListScreen = "OK";
                GameService = "Remember";
                bu = "Accept";
                bv = "Cancel";
                bw = "Select";
                bx = "Enter";
                by = "Open link";
                bz = "New character";
                bA = "Back";
                bB = "Kill";
                bC = "Kill boss";
                bD = "gold";
                bE = "gem";
                bF = "ruby";
                bG = "You PK point is ";
                bH = " attacks you";
                bI = "Not enough KI to use";
                bJ = "You have received";
                bK = "You have learnt ";
                bN = "Friend";
                bO = "Enemy";
                bP = "No friend";
                bQ = "World chat";
                bR = "Change flag";
                bU = "Option";
                bV = "Increase resolution (strong devices)";
                bW = "Decrease resolution (weak devices)";
                bX = "Server notice";
                cb = "Special aura";
                Npc = "Power aura";
                bZ = "Small screen";
                bY = "Big screen";
                ca = "Do you want to exit game to change screen size?";
                cd = "Chest";
                ItemMap = new String[]{"Chest", ""};
                cf = new String[]{"Inven-", "tory"};
                cg = new String[]{"Combine", ""};
                ch = new String[]{"Map", ""};
                ci = new String[]{"Give", "item"};
                cj = new String[]{"Receive", "item"};
                ck = new String[]{"Zone", ""};
                cl = "Zone";
                cm = "Map";
                cn = "Receive item";
                co = "Receive";
                cp = "Receive All";
                cq = "Go to the flashing point on the map for quest";
                cr = "For Earth only\n";
                cs = "For Namekian Only\n";
                ct = "For Xaiyan Only\n";
                cu = "Power required";
                cv = "Your power";
                cw = "Used";
                cx = "place";
                cy = "Upgrade";
                cz = "Upgrading";
                cA = "Add\nShort cut";
                cB = "Into\nplace ";
                cC = "Move to\nchest";
                cD = "Move to\nchest";
                cE = "Chat";
                cF = "Miss";
                cG = "Donate";
                cH = "Receive";
                cI = "Double Tap";
                cJ = "Can harvest";
                cK = "Press Y to accept (";
                cL = "Press # to accept (";
                cM = "Please restart game to update data";
                cN = "Online";
                cO = "Offline";
                cP = "Make friend";
                cQ = "Chat player";
                cR = "Chat with";
                cS = "Capsule Donate";
                cT = "Personal Capsule";
                cU = "Clan'SessionReceiver Capsule";
                cV = "Give bean";
                cW = "Receive bean";
                cX = "Request bean";
                cY = " time";
                cZ = "Received";
                da = "Power";
                db = "Join date";
                dc = "Clan Leader";
                dd = "Clan coleader";
                de = "Power points";
                df = "Member";
                BaseCanvas = new String[]{"Member", ""};
                dh = new String[]{"Chat", "clan"};
                mFont = new String[]{"Leave", "clan"};
                dj = new String[]{"Create", "clan"};
                dk = new String[]{"Find", "clan"};
                dl = new String[]{"Slogan"};
                dm = new String[]{"Icon"};
                dn = new String[]{"Request", "bean"};
                cfr_renamed_0 = "Level";
                dp = "Clan birthday";
                dq = "Clan list";
                dr = "Not joint clan";
                ds = new String[]{"You are the only one", " member of this clan.", " Someone may request to join.", " You can select other players", " to invite them join clan"};
                dt = "Enter clan'SessionReceiver name";
                du = "Clan'SessionReceiver name";
                dv = "Clan chat";
                dw = "Enter clan'SessionReceiver name you want to create";
                dx = "Enter clan'SessionReceiver slogan";
                dy = "Do you want to join clan ";
                dz = "Select clan'SessionReceiver icon";
                dA = "Request join\nclan";
                dB = "View clan'SessionReceiver\nmember";
                dC = "Order\ncoleader";
                dD = "Order\nleader";
                dE = "Dismiss";
                dF = "Kick member";
                dG = "Please enter clan'SessionReceiver name";
                dH = "Please enter clan'SessionReceiver slogan";
                dI = "Can not find clan";
                dJ = "ago";
                dK = "Finding clan";
                dL = "Trade";
                dM = " didn'MyHashtable lock transaction";
                dN = "Transaction is not locked";
                dO = " locked transaction";
                dP = "Transaction is locked";
                dQ = "Lock transaction";
                dR = "Wait opponent to lock transaction";
                dS = "Press 'Done'";
                dT = "Done";
                dU = "Opponent";
                dV = "You";
                dW = "Lock";
                dX = "Transaction amount";
                dY = "Move to Equipment";
                dZ = "Remove";
                eb = "Sale";
                ec = "Enter money to trade";
                WeatherEffect = "Enter money";
                ee = "Enter wrong amount, please try again";
                ef = "Not enough money, please try again";
                eg = "Enter quantity you want to trade";
                eh = "Enter quantity";
                ei = "Enter wrong quantity, please try again";
                ej = "You already have this item";
                ek = "Please unlock before trade this item";
                MyVector = "Base";
                SplashScreen = "need";
                mGraphics = "Need";
                Position = "Free";
                ep = "Select item";
                eq = "Random";
                er = "Hello!";
                es = "What do you want to buy?";
                et = "What do you want to lear?";
                eu = "Are you sure you want to trade with those items?";
                ev = "Learn with";
                ew = "Buy with";
                ex = "You can not perform this action when dying";
                ey = "Use\nfor\ncombine";
                ez = "Use\nfor\ntrade";
                eA = "You don'MyHashtable have enough gem to chat on world channel";
                eB = "Chat on world channel (5 gems)";
                eC = " want to trade with you, do you accept?";
                eD = "You have just upgrade ";
                eE = " to ";
                eF = "potential to Master to learn";
                eG = "Potential points";
                eH = "Achievement point";
                eI = "increase";
                eJ = "Increase";
                eK = "You only have ";
                eL = " potential pts. Let'SessionReceiver practice more to earn ";
                eM = "Do you want to use ";
                eN = " potential pts to add ";
                eO = " for HP?";
                eP = " for KI?";
                eQ = " for attack?";
                eR = " for critical?";
                eS = "At ";
                eT = " potential points, you can upgrade for free ";
                eU = ". Or see Uron to buy recipes faster.";
                eV = "Crit Dame";
                eW = "Re.Dame";
                eX = "HP";
                eY = "KI";
                eZ = "Attack";
                fa = "Armor";
                fb = "Vitality";
                fc = "Crit";
                fd = "Level";
                fe = "KI consume: ";
                ff = "Cooldown";
                fg = "Maximum level reached";
                fh = "Next level required ";
                fi = "potential";
                fj = "Not learnt";
                fk = "Require ";
                fl = "Learn";
                fm = "to gain 20 HP";
                fn = "to gain 20 MP";
                fo = "to gain 1 power point";
                fp = new String[][]{{"Gohan", "Krillin", "Yamcha"}, {"Dende", "Piccolo", "Kami"}, {"Vegeta", "Raditz", "Kakarot"}};
                if (Res.clientType == 7) {
                    fp = new String[][]{{"Hango", "Linkhi", "Chayam"}, {"Deden", "Cololo", "Mika"}, {"Tageve", "Ditra", "Rotkaka"}};
                }
                fq = "Quest place";
                fr = "You don'MyHashtable have quest";
                fs = "Complete, reward ";
                ft = "Achievement quest";
                fu = "Equipment";
                fv = "What do you want to do";
                fw = "Select";
                fx = "Select";
                fy = "Select your destination";
                fz = "OK to disable World Channe";
                fA = "OK to enable world channel";
                gh = "New game";
                gi = "Play acc";
                gk = "Not register yet";
                go = "potential to Whis to learn";
                return;
            }
            case 2: {
                ServerListScreen.Res = "http://dragonball.indonaga.com";
                x.j = Res.loadImage("/mainImage/logo1E.png");
                bz.LoginScreen();
            }
        }
    }
}

